vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        organizers:
            uri_prefix: /uploads/organisers
            upload_destination: '%kernel.project_dir%/public/uploads/organisers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        sponsors:
            uri_prefix: /uploads/sponsors
            upload_destination: '%kernel.project_dir%/public/uploads/sponsors'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        speakers:
            uri_prefix: /uploads/speakers
            upload_destination: '%kernel.project_dir%/public/uploads/speakers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
